### ISSUE TITLE
Fail to update market data for BTC on testnet

### ISSUE THREAD

**Issue by think-in-universe** [liquality/atomicagent#361]
### Description

Received the below error when running atomic agent locally, so cannot update market data for BTC. 

```
o [NodeError]
    at r._handleNodeError (/.../liquality/atomicagent/node_modules/@liquality/node-provider/dist/index.js:1:1508)
    at /.../liquality/atomicagent/node_modules/@liquality/node-provider/dist/index.js:1:1882
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  error: 'Invalid "addresses" field'
}
```

This is probably because the addresses are `[]` here, when updating market data for BTC: https://github.com/liquality/atomicagent/blob/a054c02e525a030f7e6c84f4832f582bf7ca5425/src/models/Market.js#L91    

The BTC configuration. 

```toml
  [assets.BTC]
  blockTime = "1 minute"
  network = "bitcoin_testnet"
  addressType = "bech32"
  swapMode = "p2wsh"
  feeNumberOfBlocks = 2
  defaultFee = "average"
    [assets.BTC.api]
    url = "https://liquality.io/testnet/electrs"
    [assets.BTC.batchApi]
    url = "https://liquality.io/electrs-testnet-batch/"
    [assets.BTC.wallet]
    type = "js"
    mnemonic = "<seed phrase>"
```
